# Generated by Django 3.2.16 on 2022-11-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('your_polls', '0003_auto_20221127_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PollsGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='your_polls.poll')),
            ],
        ),
    ]
