# Generated by Django 3.2.16 on 2022-11-26 18:11
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('your_polls', '0002_auto_20221127_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
