# Generated by Django 3.2.16 on 2022-11-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('your_polls', '0003_auto_20221127_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_hash',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='analytics.userhash'),
            preserve_default=False,
        ),
    ]
